name: Go build

on:
  workflow_call:
    inputs:
      workspace:
        description: go module workspace
        required: false
        type: string
        default: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"
          cache-dependency-path: ${{ inputs.workspace }}/go.sum
      - name: Set up netrc
        uses: extractions/netrc@v1
        with:
          machine: buf.build
          username: ${{ secrets.BUF_USERNAME }}
          password: ${{ secrets.BUF_TOKEN }}
      - name: Set up github netrc
        uses: extractions/netrc@v1
        with:
          machine: github.com
          username: ${{ secrets.GH_PACKAGES_ORG_USERNAME }}
          password: ${{ secrets.GH_PACKAGES_ORG_TOKEN }}
      - name: Go lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
          working-directory: ${{ inputs.workspace }}
          args: --timeout=10m
      - name: Go build
        run: go build -v ./${{ inputs.workspace }}/...
      - name: Go test
        run: go test -v ./${{ inputs.workspace }}/...
