name: Copy image to aliyun

on:
  workflow_call:
    outputs:
      success:
        value: {{ jobs.ret-outputs.success }}
      timeout:
        value: {{ jobs.ret-outputs.timeout }}
    inputs:
      project:
        description: 'the name of project to be built and the corresponding image'
        required: true
        type: string
      tag:
        description: 'the image tag'
        required: true
        type: string

    secrets:
      ACR_ADMIN_USERNAME:
        required: true
      ACR_ADMIN_PASSWORD:
        required: true
      ACR_USERNAME:
        required: true
      ACR_PASSWORD:
        required: true
      AZURE_KUBE_CONFIG:
        required: true

env:
  AZURE: coseus.azurecr.io
  ALICLOUD: registry.cn-hangzhou.aliyuncs.com/coscene

jobs:
  copy-image-to-aliyun:
    needs:
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
      - name: Skopeo Copy
        uses: coscene-io/skopeo-copy-action@v1.0.0
        env:
          AZURE: coseus.azurecr.io
          ALICLOUD: registry.cn-hangzhou.aliyuncs.com/coscene
#          http_proxy: http://gfw:7890
#          https_proxy: http://gfw:7890
        with:
          src-image: ${{ env.AZURE }}/${{ inputs.project }}:${{ inputs.tag }}
          dst-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:${{ inputs.TAG }}
          src-creds: ${{ secrets.ACR_ADMIN_USERNAME }}:${{ secrets.ACR_ADMIN_PASSWORD }}
          dst-creds: ${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}

      - name: Skopeo Copy
        uses: coscene-io/skopeo-copy-action@v1.0.0
        env:
#          http_proxy: http://gfw:7890
#          https_proxy: http://gfw:7890
        with:
          src-image: ${{ env.AZURE }}/${{ inputs.project }}:latest
          dst-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:latest
          src-creds: ${{ secrets.ACR_ADMIN_USERNAME }}:${{ secrets.ACR_ADMIN_PASSWORD }}
          dst-creds: ${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}

  sync-fallback:
    needs:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Skopeo Copy
        uses: coscene-io/skopeo-copy-action@v1.0.0
        with:
          src-image: ${{ env.AZURE }}/${{ inputs.project }}:${{ inputs.tag }}
          dst-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:${{ inputs.tag }}
          src-creds: ${{ secrets.ACR_ADMIN_USERNAME }}:${{ secrets.ACR_ADMIN_PASSWORD }}
          dst-creds: ${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}

      - name: Skopeo Copy latest
        uses: coscene-io/skopeo-copy-action@v1.0.0
        with:
          src-image: ${{ env.AZURE }}/${{ inputs.project }}:latest
          dst-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:latest
          src-creds: ${{ secrets.ACR_ADMIN_USERNAME }}:${{ secrets.ACR_ADMIN_PASSWORD }}
          dst-creds: ${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}

  ret-output:
    outputs:
      success: ${{ steps.is-successful.outputs.result }}
      timeout: ${{ steps.is-timout.outputs.result }}
    needs:
      - copy-image-to-aliyun
      - sync-fallback
    steps:
      - name: Success
        id: is-successful
        if: needs.copy-image-to-aliyun.result == 'success' || needs.sync-fallback.result == 'success'
        run: echo "result=true" >> $GITHUB_OUTPUT
      - name: Timeout
        id: is-timeout
        if: needs.copy-image-to-aliyun.result == 'cancelled' && needs.copy-image-to-aliyun.result == 'cancelled'
        run: echo "result=true" >> $GITHUB_OUTPUT
