name: Copy image to volcengine

on:
  workflow_call:
    inputs:
      project:
        description: 'the name of project to be built and the corresponding image'
        required: true
        type: string
      tag:
        description: 'the image tag'
        required: true
        type: string

env:
  ALICLOUD: registry.cn-hangzhou.aliyuncs.com/coscene
  VOLCENGINE: coscene-cn-shanghai.cr.volces.com/coscene

jobs:
  cp-image-use-gh:
    runs-on: ["self-hosted", "aliyun", "X64"]
    timeout-minutes: 5
    continue-on-error: true
    steps:
      - name: Skopeo Copy
        uses: coscene-io/skopeo-copy-action@v1.0.0
        with:
          src-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:${{ inputs.tag }}
          dst-image: ${{ env.VOLCENGINE }}/${{ inputs.project }}:${{ inputs.tag }}
          src-creds: ${{ secrets.ACR_USERNAME  }}:${{ secrets.ACR_PASSWORD  }}
          dst-creds: ${{ secrets.VOLCENGINE_CR_USERNAME }}:${{ secrets.VOLCENGINE_CR_PASSWORD }}
