name: Copy image to aliyun

on:
  workflow_call:
    inputs:
      project:
        description: 'the name of project to be built and the corresponding image'
        required: true
        type: string
      tag:
        description: 'the image tag'
        required: true
        type: string

env:
  AZURE: coseus.azurecr.io
  ALICLOUD: registry.cn-hangzhou.aliyuncs.com/coscene

jobs:
  cp-image-use-gh:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    steps:
      - name: Skopeo Copy
        uses: coscene-io/skopeo-copy-action@v1.0.0
        with:
          src-image: ${{ env.AZURE }}/${{ inputs.project }}:${{ inputs.tag }}
          dst-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:${{ inputs.tag }}
          src-creds: ${{ secrets.ACR_ADMIN_USERNAME }}:${{ secrets.ACR_ADMIN_PASSWORD }}
          dst-creds: ${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}

      - name: Skopeo Copy latest
        uses: coscene-io/skopeo-copy-action@v1.0.0
        with:
          src-image: ${{ env.AZURE }}/${{ inputs.project }}:latest
          dst-image: ${{ env.ALICLOUD }}/${{ inputs.project }}:latest
          src-creds: ${{ secrets.ACR_ADMIN_USERNAME }}:${{ secrets.ACR_ADMIN_PASSWORD }}
          dst-creds: ${{ secrets.ACR_USERNAME }}:${{ secrets.ACR_PASSWORD }}
