name: Probe Volcengine latest copy

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Image project to copy"
        required: true
        type: string
        default: data-platform-web
      tag:
        description: "Release tag to copy"
        required: true
        type: string
        default: 2026-06-04-v26.23.4-rc1

jobs:
  probe:
    uses: ./.github/workflows/cp-image-to-volcengine.yml
    with:
      project: ${{ inputs.project }}
      tag: ${{ inputs.tag }}
    secrets: inherit
