name: Sub-chart Upgrade

on:
  workflow_call:
    inputs:
      runner:
        description: "Runner label to run on"
        required: false
        type: string
        default: ubuntu-latest
      deployment-name:
        description: 'the name of deployment to be upgraded'
        required: true
        type: string

jobs:
  sub-chart-upgrade:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 1
    steps:
      - name: Set up CD tools
        uses: coscene-io/setup-cd-tools@v2.1.1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          kubectl: '1.22.2'
      - name: VKE login
        uses: azure/k8s-set-context@v5
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.VOLCENGINE_DEV_KUBE_CONFIG }}
      - name: Restart pods about target sub-chart
        run: |
          kubectl rollout restart deployment/${{ inputs.deployment-name }} -n coscene
      - name: Notification to Feishu
        uses: coscene-io/cicd-templates/.github/actions/feishu-notify@824434d6b2fc762f55f112adec821a36ac161b46
        with:
          webhook-url: ${{ secrets.FEISHU_BOT_WEBHOOK_URL_RHODE_ISLAND }}
          text: |
            Sub-chart upgrade!
            the deployment ${{ inputs.deployment-name }} restarted.
            GitHubEvent: ${{ github.event_name }}
            committer: ${{ github.actor }}
            baseRef: ${{ github.ref }}
